baseurl = "http://www.ubcchemecar.com/"
title = "UBC Chem-E-Car: The University of British Columbia"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "ubcchemecar"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-63367875-1"
canonifyurls = true
# Define the number of posts per page
paginate = 10

[params]
    viewMorePostLink = "/blog/"
    author = "UBC Chem-E-Car"
    about_us =  """
                <p>UBC Chem-E-Car is a student-driven engineering team that represents the University of British Columbia in the annual AIChE Chem-E-Car competition.</p>
                <p>Email Us: <b><a href="mailto:team@ubcchemecar.com">team@ubcchemecar.com</a></b></p>
                """
    copyright = "Copyright (C) 2017 UBC Chem-E-Car. All rights reserved."
    date_format = "2006-01-02"
    logo = "img/logo2.png"
    address =   """
                 <p><strong>UBC Chem-E-Car Team</strong>
                 <br><i>Chemical and Biological Engineering Building</i>
                 <br>2360 East Mall
                 <br>Vancouver V6T 1Z3
                 <br>British Columbia, <strong>Canada</strong>
                 </p>
                """
    meeting =   """
                 <p><strong>2016-2017 Term 2 (January-April)</strong>
                 <br>Saturday 12pm, CHBE 103
                 <br>Wednesday 6pm, CHBE 103
                 <br><i>Meeting times may change, sign up for the <a href="..\/infopack">mailing list</a> and check your email!</i>
                 </p>
                """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[[params.menu]]
    name = "Home"
    url  = "/"
    weight = 1

[[params.menu]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[params.menu]]
    name = "Sponsors"
    url  = "/sponsors/"
    weight = 3

[[params.menu]]
    name = "Recruitment"
    url  = "/infopack/"
    weight = 4

[[params.menu]]
    name = "Team"
    url  = "/team/"
    weight = 5

[[params.menu]]
    name = "Services"
    url  = "/services/"
    weight = 6

[[params.menu]]
    name = "Contact"
    url  = "/contact/"
    weight = 7

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.features]
    # enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Teams"
    subtitle = "The UBC Chem-E-Car team consists of 5 main sub-teams with different roles. We have many members who work hard to make the car and all of our side projects a reality! Meet our team leads and learn more about what they do on the team."

[params.see_more]
    enable = true
    icon = "fa fa-users"
    title = "Get more team information"
    subtitle = "Visit our team page to see all team members and view the team roster"
    link_url = "#"
    link_text = "Team Page"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Sponsors"
    subtitle = "We'd like to thank the following organizations for their kind support and various contributions, without which this project would not have been possible. Please find more information on the great work that they do on our sponsors page."

[params.about]
    title = "About Us"
    description = "UBC Chem-E-Car represents The University of British Columbia in the annual American Institute of Chemical Engineers (AIChE) Chem-E-Car competition where we compete with other North American teams. We design, build and test a shoe-box sized car from scratch every year. The process involves building a power system (batteries, fuel cells, supercapacitors etc), selecting a stopping mechanism reaction, designing the circuitry, coding microcontrollers and assembling the mechanical components and car body."


[params.sponsorship]
    title = "Our Valued Supporters"
    description = "We'd like to thank our sponsors for their kind support and various contributions, without which our student-led projects would not have been possible. As a sponsor, your contributions help fund student development and professional growth for undergraduate students."


[params.recent_posts]
    enable = true
    title = "Latest and Greatest"
    subtitle = "Read our articles to learn more about what we are working on. Occasionally, we also share tutorials on electrochemistry, mechanical design, software development and other fun topics that we came across."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/athanasios-kritharis-180693a5"
    image = "/img/team/2015/thanos.jpg"
    name = "Thanos Kritharis"
    role = "Captain"
    blurb = "Athanasios (Thanos) is currently in his 3rd year of involvement with Chem-E-Car. He has watched the team grow from 5 dedicated students to the 30+ Organization that it is today. Under his leadership Chem-E-Car has expanded to include innovations in the LNG sector, development of novel forms of rechargeable batteries, and increased public outreach and education on fuel cells and other forms of energy storage. He hopes to further empower even more students in pursuing their passion to develop technologies for the benefit of all."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/c-siang-lim-98535048"
    image = "/img/team/2017/siang.jpeg"
    name = "Siang Lim"
    role = "Vice-Captain/Administration"
    blurb = "Siang is in his final year of his degree. Siang manages the website, prepares team documents and manages the Chem-E-Car Brand. In his spare time... Just kidding, Siang does not believe in spare time."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/ngai-to-lo-7a6750129"
    image = "/img/team/2017/ngaito.jpeg"
    name = "Ngai To Lo"
    role = "Logistics Officer/Senior Electrical Lead"
    blurb = "Ngai To is a 3rd year chemical engineering student participating in Chem-E-Car as the Head of Logistics and Electrical Lead. Ngai To enjoys a little bit of everything and tinkers with mechanics, machining, coding, and hardware in his free time."

[[params.team]]
    linkedin = ""
    image = "/img/team/2015/marcCaruth.jpg"
    name = "Marc Caruth"
    role = "Treasurer, Sponsorship"
    blurb = "Marc Caruth is currently in his 2nd year of involvement with Chem-E-Car. Marc is responsible for the financials including preparing the budget and reporting the actual results. In his free time, he enjoys skiing and hiking in the Vancouver mountains."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/andrew-may-1b31b796"
    image = "/img/team/2017/andy.jpg"
    name = "Andrew May"
    role = "Senior Chemical Team Member"
    blurb = ""

[[params.team]]
    linkedin = ""
    image = "/img/team/negar.jpg"
    name = "Negar Zaghi"
    role = "Chemical Team Lead"
    blurb = ""

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/weiraybi"
    image = "/img/team/2017/ray.jpeg"
    name = "Ray Bi"
    role = "Chemical Team Lead"
    blurb = "Ray is an enthusiastic and detail-oriented 3rd year student in CHBE with high awareness of potential resource crisis and severe environment pollution. He finds it challenging, but exciting and enjoyable in proposing and optimizing stopping mechanisms and biofuel utilization methods. He is looking forward to devoting more time and energy into the delightful collaboration with colleagues in Chem-E-Car with similar pursuit and aspiration in the following years."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/vasiliy-triandafilidi-01326770"
    image = "/img/team/vasiliy.png"
    name = "Vasilii Triandafilidi"
    role = "Graduate Student Advisor"
    blurb = "Vasilii is a PhD student in the Department of CHBE working on simulation of stimuli responsive polymers. Currently Vasilii is in his first year of involvement with Chem-E-Car as graduate advisor. He provides technical support for the team through his expertise in programming and materials engineering."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/shayanrezaie"
    image = "/img/team/shayan.jpg"
    name = "Shayan Rezaie"
    role = "Electrical Team"
    blurb = "Shayan is a fifth year Engineering physics student who is responsible for designing the schematics and PCB for the Chem-E-Car . He is also involved in developing the code/drivers for the sensors used in this project. Before joining Chem-E-Car, Shayan worked for multiple companies as a hardware engineer developing software and schematics."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/arjun-bhagwat-7b6345b6"
    image = "/img/team/2017/arjun.jpg"
    name = "Arjun Bhagwat"
    role = "Senior Battery Team Member"
    blurb = ""

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/kyle-como-9524b990"
    image = "/img/team/2017/kyle.jpeg"
    name = "Kyle Como"
    role = "Mechanical Lead"
    blurb = "I am an undergraduate student in my 3rd year of Mechanical Engineering. My goal is to explore all of the exciting mechanical design options with my teammates and to produce prototypes. Before UBC I worked as a Mechanical Designer for 5 years. I have a diploma as a Mechanical Engineering Technologist in manufacturing from the BCIT and also as a Computer Automated Systems Technician from Thompson Rivers University. I will be conducting 3D modelling courses throughout the school year with the intent of manufacturing and prototyping."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/kirsten-meng-49935bb3"
    image = "/img/team/2015/kirsten.jpg"
    name = "Kirsten Meng"
    role = "Mechanical Team"
    blurb = "Kirsten is a Mechanical Engineering student! Woohoo!"

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/mani-massah-172907b0"
    image = "/img/team/mani.jpg"
    name = "Mani Massah"
    role = "Battery Lead"
    blurb = "Mani is a 4th year chemical engineering student with an interest in electrochemistry. He is working on creating alkaline batteries as an alternative to the zinc air batteries that are currently being used in the car. He has recently become very involved with Chem-E-Car and loves hanging out with the team."

[[params.team]]
    image = "/img/team/2015/tampriye.jpg"
    name = "Tampriye Asawo"
    role = "Logistics, Sponsorship"
    blurb = "Tampriye is a third year Chemical Engineering student. She joined Chem-E-Car in 2015 and will be using SolidWorks to design the battery compartment and prepare an appropriate electrolyte solution. She is also involved in administrative duties such as promoting the team. In her spare time, Tampriye enjoys reading and hiking various BC trails."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/dominic-bartlomowicz-149321ba"
    image = "/img/team/dominic.jpg"
    name = "Dominic Bartlomowicz"
    role = "Creative Director"
    blurb = "I am a 4th year Chemical and Biological Engineering student. My areas of greatest interest lie in environmental and ecological preservation alongside medical advancements and disease control. As an individual with a strong international background, I am often enthusiastic to explore new parts of the world and gain alternate perspectives on human culture. In my free time, I am an avid musician and play multiple instruments in addition to exploring the depths of musical production."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/claire-armour-a1681181"
    image = "/img/team/2015/claire.jpg"
    name = "Claire Armour"
    role = "Sponsorship Lead"
    blurb = "Claire joined Chem-E-Car in May 2015. As sponsorship officer, she is responsible for securing funding for the team. In her spare time, Claire volunteers with UBC Intramuralss. She enjoys playing the piano and questioning her degree."


[[params.team]]
    linkedin = "https://ca.linkedin.com/in/jordan-wright-53a606108"
    image = "/img/team/2015/jordan.jpg"
    name = "Jordan Wright"
    role = "Junior Battery Lead"
    blurb = "Jordan joined the battery team in 2015 to assist with the research and development of the new battery. He is a second year Chemical Engineering student with an interest in electrochemical cells and energy-related biotechnologies. He enjoys playing his guitar in his free time, as well as watching movies and playing League of Legends. Jordan is currently on a co-op term in Montreal."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/victor-chiew-b7359185"
    image = "/img/team/2017/victor.jpeg"
    name = "Victor Chiew"
    role = "Junior Team Co-captain"
    blurb = ""

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/abhishek-lekhi-171160105"
    image = "/img/team/2017/abhi.jpg"
    name = "Abhishek Lekhi"
    role = "Junior Team Co-captain"
    blurb = "Second year CHBE student"

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/said.jpeg"
    name = "Said Zaid"
    role = "Junior Team Vice-Captain/Sponsorship officer"
    blurb = ""

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/sequoyah.jpeg"
    name = "Sequoyah Ezekiel"
    role = "Finance and logistic officer"
    blurb = ""

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/joshua-agarwal-3b68667a"
    image = "/img/team/2017/josh.jpg"
    name =  "Josh Agarwal"
    role = "Junior Chemical Team Co-Lead"
    blurb = "Josh is a recent member of the chem e car team and currently is one of the junior chemical team lead. As a second year chemical and biological engineering student, Josh has goals to eventually work in the field of chemical tissue engineering with regenerative medicines. Hobbies include playing soccer and sketching. "

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/jayg.jpg"
    name = "Jayg Dimayacyac"
    role = "Junior Chemical Team Co-Lead"
    blurb = ""

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/ping.jpeg"
    name = "Ping Ang"
    role = "Junior Chemical Team Member"
    blurb = ""

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/nina.jpeg"
    name = "Nina Hamard"
    role = "Junior Chemical Team Member"
    blurb = ""

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/joshagustin.jpeg"
    name = "Josh Agustin"
    role = "Junior Chemical Team Member"
    blurb = ""

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/rolando.jpeg"
    name = "Rolando Streber"
    role = "Junior Chemical Team Member"
    blurb = ""

[[param.team]]
    linkedin = ""
    image = "/img/team/2017/pranav.jpeg"
    name = "Pranav Misri"
    role = "Junior Chemical Team Member"
    blurb = ""

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/jaspreet-chahal-a089ba95"
    image = "/img/team/2017/jaspreet.jpeg"
    name = "Jaspreet Chahal"
    role = "Junior Battery Team Co-Lead"
    blurb = "Jaspreet is the co-lead of the Junior Chem-E-Car Battery Team and leads the Aluminum Carbon battery team. She is in her final year of Chemical Engineering ( Process Option ) and her goal is to become a Process/ Project Engineer after graduation. She loves iced coffee and in her free time, she likes to watch movies/ documentaries."

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/fiona.jpeg"
    name = "Fiona D'Silva"
    role = "Junior Battery Team Co-lead/Fuel Cell Division member"
    blurb = ""

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/clement.jpeg"
    name = "Clement Asiedu-Antwi"
    role = "Safety Officer/Junior Battery Team Member"
    blurb = ""

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/stuthi-hegde-0b5403111"
    image = "/img/team/stuthi.jpg"
    name = "Stuthi Hegde"
    role = "Junior Battery Team member - Fuel Cell Division"
    blurb = "Stuthi is a second year chemical engineering student who is a recent addition to the Chem-E-Car team. She will be working on researching and developing an efficient battery for the Car. Beyond her engineering life, Stuthi enjoys traveling and hanging out with friends."

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/jeffery.jpeg"
    name = "Jeffery Kung"
    role = "Junior Battery Team member - Fuell Cell Division"
    blurb = ""

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/aziz.jpeg"
    name = "Abdulaziz Al Said"
    role = "Junior Battery Team Member"
    blurb = ""

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/shams-elnawawi-7a105810b"
    image = "/img/team/2017/shams.jpg"
    name = "Shams Elnawawi"
    role = "Junior Electrical Team Co-Lead"
    blurb = ""

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/alisa-dmitrieva-a95559124"
    image = "/img/team/2017/alisa.jpg"
    name = "Alisa Dmitrieva"
    role = "Junior Electrical Team Member"
    blurb = ""

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/caitlin.jpeg"
    name = "Caitlin Lee"
    role = " Junior Mechanical Team Co-Lead"
    blurb = "Caitlin is a 2nd year chemical engineering student. Not only is she capable of whipping up 3D parts using SolidWorks in 2 seconds or styling a chassis in 3, she also heads the UBC Dance Horizons Club. Because being lead for just one project is never enough."

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/breanna-gowe-a06b23132"
    image = "/img/team/2017/breanna.jpeg"
    name = "Breanna Gowe"
    role = "Junior Mechanical Team Co-Lead"
    blurb = "Breanna is in second year mechanical engineering and is one of the junior mechanical leads on the team. She is looking to pursue a career in the biomedical field. Outside of school Breanna likes to waterski in the Okanagan"

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/roger.jpeg"
    name = "Roger Xiao"
    role = "Junior Mechanical Team Member"
    blurb = ""

[[params.team]]
    linkedin = ""
    image = "/img/team/2017/wendie.jpeg"
    name = "Wendie Wu"
    role = "Junior Mechanical Team Member"
    blurb = ""

[[params.team]]
    linkedin = "https://ca.linkedin.com/in/filippo-botta-60b77198"
    image = "/img/team/filippo.jpg"
    name = "Filippo Botta"
    role = "Battery Team"
    blurb = "Filippo is a 4th year Chemical Engineer student. He joined Chem-E-Car this year to help with the research and development of a new battery unit. He is also involved in the design of the new battery casing. In his free time, he enjoys playing football and watching movies."

# [[params.team]]
#     linkedin = "https://ca.linkedin.com/in/solmon-dikran-8a2371117"
#     image = "/img/team/2015/solomon.png"
#     name = "Solomon Dikran hello"
#     role = "Battery Team"
#     blurb = "Solomon is a second year chemical engineering student. He has joined the team hoping to be a part of the devlopment of the battery, and also start new side projects. In his spare time Solomon enjoys playing sports, and hanging out with friends."


[[params.team]]
    linkedin = ""
    image = "/img/team/heya.jpg"
    name = "Heya Gupta"
    role = "Battery Team"
    blurb = "Heya is a first year engineerig student who joined chem-e-car in 2016. She is eager to learn and hopes to join valuable experience by being apart of this team."
